name: LockStore
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.18
  provider: ^6.1.2
  go_router: 5.1.2
  dio: ^4.0.6
  http: any
  scope_function: ^1.0.2
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.4
  expandable: ^5.0.1
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  firebase_auth: ^4.17.8
  firebase_analytics: ^10.8.9
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  url_launcher: ^6.2.5
  timeago: ^3.6.1
  json_path: ^0.7.1
  auto_size_text: ^3.0.0
  responsive_grid: ^2.4.4
  cached_network_image: ^3.3.1

  intl: any
  bloc: ^8.1.3
  adaptive_breakpoints: ^0.1.7
  dual_screen: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: any

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-Regular.ttf
    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/RobotoSerif-Regular.ttf

    - family: SF
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600

